### PR TITLE
CLDF creation via cldfbench

### PR DESCRIPTION
**Pull request by J22Melody**
Similarly as did in https://github.com/cldf-datasets/segbo, use Git submodule to import the raw data and then convert it into 4 tables.

- `values.csv`: all the phonemes with their inventory foreign keys, a few additional fields
- `contributions.csv`: all the inventories with all the joined fields from the four sources
- `languages.csv`: all the languages with all the joined fields from `glottolog_languoid.csv`
- `parameters.csv`: just the phonemes

@bambooforest I found some rows missing the field `Glottocode` in https://github.com/bdproto/bdproto/blob/master/bdproto.csv, so currently in `values.csv` there are also some rows that miss the foreign key `Language_ID` thus cause error when validating, how should we fix this? Make this optional or try to add it?

@xrotwang every time I run `cmd_makecldf`, the `requirements.txt` is updated to all the pip modules I currently have, which I guess it caused by a call here https://github.com/cldf/cldfbench/blob/master/src/cldfbench/util.py#L13. It is a bit annoying when I end up with unrelated modules such as segbo (installed when I last time worked on segbo) in `requirements.txt`, currently I uninstall it manually to make it clean, do you have a idea how to deal with this issue? Should we use a clean new Python environment every time we create a new CLDF Dataset?

Please review on it, thanks!

### CODE REVIEW

**Comment by bambooforest** [comment]
@J22Melody -- good question. So there are NA glottocodes for these data points:

   BdprotoID Glottocode SourceLanguageName   
       <dbl> <chr>      <chr>                
 1      1053 <NA>       ALTAIC               
 2      1059 <NA>       AUSTRALIAN           
 3      1090 <NA>       FINNO-PERMIC         
 4      1068 <NA>       FINNO-UGRIC          
 5      1055 <NA>       NOSTRATIC            
 6      1114 <NA>       URALO-SIBERIAN       
 7        11 <NA>       Proto-Tibeto-Burman  
 8        60 <NA>       Proto-Mamore-Guapore 
 9        64 <NA>       Proto-Totozoquean    
10        82 <NA>       Proto-Finno-Saamic   
11        84 <NA>       Proto-Finno-Permic   
12        87 <NA>       Proto-Baltic-Finnic  
13       135 <NA>       Proto-Tibeto-Burman  
14       148 <NA>       Proto-Nilo-Saharan   
15       161 <NA>       Proto-Eastern-Oceanic
16       165 <NA>       Proto-Irish    

We will write the reasoning in the BDPROTO README, but the tl;dr is that they don't have glottocodes

- because they shouldn't because no believes it existed, e.g. Altaic
- editors of the Glottolog don't believe the source
- is some intermediate node in the tree with nothing to link to

@xrotwang -- is there a standardized "NA" protocol for special codes along the line of:

https://en.wikipedia.org/wiki/ISO_639-3#Special_codes

but I guess nothing fits here, i.e. 'mis' is intended for missing codes -- and above some of these will never be added. (One option of course is drop them, but it may be nice to have them for historical purposes -- we're still discussing that.)

So @J22Melody -- I guess just NA or "None" for the time being.

**Comment by LinguList** [comment]
In our lexibank datasets, we have the practice of simply not listing Glottocodes if they are not there. So this would what I'd also recommend here.

**Comment by LinguList** [comment]
If you want to link to some additional resource, like Wikipedia, expanding the LanguageTable when adding it as a component should be also straightforward and can actually add any kind of column:

https://github.com/cldf-datasets/saphon/blob/1984d0bd6991d13416a231efc8dc85e91c4e2c8e/cldfbench_saphon.py#L132-L133

**Comment by bambooforest** [comment]
@LinguList -- thanks! So we should simply leave the Glottocodes blank @J22Melody and we can add a table to external resources (but first I would have to get the links between the non-glottocode entries and some external links).

**Comment by J22Melody** [comment]
> @LinguList -- thanks! So we should simply leave the Glottocodes blank @J22Melody and we can add a table to external resources (but first I would have to get the links between the non-glottocode entries and some external links).

OK I have made those 'NA' entries to be blank and now it's good since the `Language_ID` field is by default optional.

I am going to merge this PR if all good. I guess the external resource table could be done a bit later.

**Comment by bambooforest** [comment]
@xrotwang -- does the contributions table look right to you? when compared to:

https://github.com/cldf-datasets/phoible/blob/master/cldf/contributions.csv

@J22Melody -- please also drop the fields:

Allophone
AllophoneNotes
LowconfidencePhonemic
Variants
LowconfidencePhonetic

they are quite useless

**Comment by J22Melody** [comment]
> @xrotwang -- does the contributions table look right to you? when compared to:
> 
> https://github.com/cldf-datasets/phoible/blob/master/cldf/contributions.csv
> 
> @J22Melody -- please also drop the fields:
> 
> Allophone
> AllophoneNotes
> LowconfidencePhonemic
> Variants
> LowconfidencePhonetic
> 
> they are quite useless

Done dropping these fields.

**Pull request merged**
